import { useEffect, useState } from "react";
import { Sparkles, Copy, Check, Wand2, Send } from "lucide-react";
import { Dialog, Button, Field, Select, Textarea, Spinner } from "../ui";
import { aiApi } from "../../lib/services";
import { toast } from "sonner";
import { useNotifications } from "../../context/NotificationContext";

const displayAIText = (value) => typeof value === "string" ? value.replace(/\$/g, "FCFA ") : value;

/**
 * AI email generator dialog. Given a lead, asks Gemini to draft a subject +
 * body for a chosen purpose & tone. The draft is editable before copying.
 */
export function AiEmailDialog({ open, onClose, lead }) {
  const [purpose, setPurpose] = useState("Follow-up");
  const [tone, setTone] = useState("Friendly & professional");
  const [loading, setLoading] = useState(false);
  const [draft, setDraft] = useState(null);
  const [copied, setCopied] = useState(false);
  const {refreshNotifications} = useNotifications();

  useEffect(() => {
    if (open && lead?._id) aiApi.results({type: "EMAIL", leadId: lead._id}).then((res) => setDraft(res.results?.[0]?.result || null)).catch(() => {});
  }, [open, lead?._id]);

  const generate = async () => {
    setLoading(true);
    try {
      const res = await aiApi.generateEmail({ leadId: lead._id, purpose, tone });
      setDraft({ subject: res.subject, body: res.body });
      await refreshNotifications();
    } catch (err) {
      toast.error(err.message || "Could not generate email");
    } finally {
      setLoading(false);
    }
  };

  const copy = () => {
    navigator.clipboard.writeText(`Subject: ${draft.subject}\n\n${draft.body}`);
    setCopied(true);
    toast.success("Email copied to clipboard");
    setTimeout(() => setCopied(false), 1800);
  };

  const send = () => {
    const recipient = lead?.email?.trim();
    if (!recipient) {
      toast.error("This lead does not have an email address");
      return;
    }

    const composeUrl = new URL("https://mail.google.com/mail/");
    composeUrl.searchParams.set("view", "cm");
    composeUrl.searchParams.set("fs", "1");
    composeUrl.searchParams.set("to", recipient);
    composeUrl.searchParams.set("su", displayAIText(draft.subject));
    composeUrl.searchParams.set("body", displayAIText(draft.body));
    window.open(composeUrl.toString(), "_blank", "noopener,noreferrer");
  };

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title="AI Email Generator"
      description={`Draft an email to ${lead?.name}`}
    >
      <div className="grid grid-cols-2 gap-3">
        <Field label="Purpose">
          <Select value={purpose} onChange={(e) => setPurpose(e.target.value)}>
            {["Follow-up", "Sales pitch", "Meeting request", "Re-engagement", "Thank you"].map(
              (p) => (
                <option key={p}>{p}</option>
              )
            )}
          </Select>
        </Field>
        <Field label="Tone">
          <Select value={tone} onChange={(e) => setTone(e.target.value)}>
            {[
              "Friendly & professional",
              "Formal",
              "Concise & direct",
              "Warm & casual",
            ].map((t) => (
              <option key={t}>{t}</option>
            ))}
          </Select>
        </Field>
      </div>

      <Button className="mt-4 w-full" onClick={generate} loading={loading}>
        <Wand2 className="h-4 w-4" /> {draft ? "Regenerate draft" : "Generate email"}
      </Button>

      {loading && <Spinner />}

      {draft && !loading && (
        <div className="mt-5 space-y-3 animate-fade-up">
          <Field label="Subject">
            <input
              value={displayAIText(draft.subject)}
              onChange={(e) => setDraft({ ...draft, subject: e.target.value })}
              className="h-10 w-full rounded-xl border border-line bg-surface px-3.5 text-sm focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-500/20"
            />
          </Field>
          <Field label="Body">
            <Textarea
              rows={9}
              value={displayAIText(draft.body)}
              onChange={(e) => setDraft({ ...draft, body: e.target.value })}
            />
          </Field>
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={send}>
              <Send className="h-4 w-4" /> Send
            </Button>
            <Button variant="outline" onClick={copy}>
              {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              {copied ? "Copied" : "Copy"}
            </Button>
          </div>
        </div>
      )}

      {!draft && !loading && (
        <p className="mt-4 flex items-center justify-center gap-1.5 text-xs text-ink-soft">
          <Sparkles className="h-3.5 w-3.5" /> Generated by Google Gemini
        </p>
      )}
    </Dialog>
  );
}
